version: '3'

services:
  db:
    image: postgres:latest
    environment:
      POSTGRES_USER: diary_user
      POSTGRES_PASSWORD: diary_password
      POSTGRES_DB: diary_app
    volumes:
      - db-data:/var/lib/postgresql/data

  backend:
    build: ./diary-backend
    command: flask run --host=0.0.0.0
    volumes:
      - ./diary-backend:/app
    environment:
      FLASK_APP: app.py
      FLASK_ENV: development
      DATABASE_URL: postgresql://diary_user:diary_password@db/diary_app
    ports:
      - '5000:5000'
    depends_on:
      - db

  frontend:
    build: ./diary-frontend
    command: sh -c 'npm install && npm start'
    volumes:
      - ./diary-frontend:/app
      - /app/node_modules
    ports:
      - '3000:3000'
    depends_on:
      - backend

volumes:
  db-data: